### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by DONOcoding** [MachineKillin/Email-Account-Generator-Checker#3]
C:\Users\DONO\Desktop\DEV\Email generator\Email-Account-Generator-Checker>python3 main.py
Traceback (most recent call last):
  File "C:\Users\DONO\Desktop\DEV\Email generator\Email-Account-Generator-Checker\main.py", line 1, in <module>
    import requests, os, threading, sys, time, random, ctypes, datetime, os.path, tkinter
ModuleNotFoundError: No module named 'requests'

**Comment by MachineKillin** [comment]
you need to install requests `python -m pip install requests`
